version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./clientes.db:/app/clientes.db
    environment:
      - ENVIRONMENT=development
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_API_URL=http://localhost:8001
    command: npm run dev

  # Opcional: Banco PostgreSQL para produção
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: harmofin
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: 