# fly.toml app configuration file generated for harmofin on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "harmofin"
primary_region = "gru"

[build]

[env]
  PORT = "8001"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "60s"
  method = "GET"
  timeout = "10s"
  path = "/health"

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 